ajout du check-in réglable
retke/bronolcord-cogs pull request #1
Opened 2020-08-10 07:55 UTC by leElvyn

ajout de la commande tournamentset_checkintime et du support pour un check-in de durée réglable jusqu'a 7 jours

2020-08-10 08:59 UTC, laggron42 requested changes
Un bon début, je pense juste que si on veut partir sur une durée variable, il faut pas rester sur un nombre de secondes brut, mais utiliser `datetime.timedelta`,  c'est pas très compliqué à utiliser et ça simplifie beaucoup les choses.
Tu peux même utiliser `redbot.core.commands.TimedeltaConverter` pour avoir de meilleurs outils pour la commande (et donner par exemple `30m`, ` 2h`, `5d12h45s`...). Faudra juste bien sauvegarder tout ça avec un nombre de secondes (`timedelta.total_seconds()`).

2020-08-10 08:59 UTC, retke commented on tournamentmanager/progress_menu.py
> +        embed.add_field(name="Temps restant", value="{0}m".format(check_time / 60), inline=False)
Utilise `datetime.timedelta` plutôt que de jouer avec le nombre de secondes. Ça te permettra d'utiliser l'attribut `strftime` pour formatter un texte propre.

2020-08-10 08:59 UTC, retke commented on tournamentmanager/tournamentmanager.py
> +    @tournamentset.command(name="checkintime")
Manque un saut à la ligne.

```suggestion

    @tournamentset.command(name="checkintime")
```

2020-08-10 08:59 UTC, retke commented on tournamentmanager/tournamentmanager.py
> +        check_time = await self.data.guild(ctx.guild).check_time()
Pas la peine d'appeler Config ici, décale plutôt l'appel dans la classe `CheckIn` directement, et donc en retirant l'argument.

2020-08-10 22:56 UTC, laggron42 requested changes
Désolé d'être chiant, mais il manque encore deux trois trucs...

2020-08-10 22:56 UTC, retke commented on tournamentmanager/progress_menu.py
> +            time=await self.data.guild(ctx.guild).check_time(),
Pourquoi appeler Config quand tu as déjà la valeur ? Retire complètement l'argument `check_time` et met plus haut quelque chose de ce genre
```py
check_time = await self.data.guild(ctx.guild).check_time()
```
Là t'appelles deux fois la même chose. Supprime complètement l'argument `check_time` de la classe.

2020-08-10 22:56 UTC, retke commented on tournamentmanager/progress_menu.py
> +        embed.add_field(name="Temps restant", value="{0}".format(timedelta(seconds=check_time)), inline=False)
J'ai du mal à comprendre l'intérêt 🤔 
```suggestion
        embed.add_field(name="Temps restant", value=str(timedelta(seconds=check_time)), inline=False)
```

2020-08-10 22:56 UTC, retke commented on tournamentmanager/tournamentmanager.py
> +        """règle la durée du check in. Doit-être en minutes."""
Utilise `TimedeltaConverter` comme je t'ai dit, et précise son fonctionnement dans la docstring. D'ailleurs essaye de suivre le même format que pour les autres commandes:
```py
async def command():
    """
    Texte avec de belles majuscules...

    Sous-texte affiché avec `!help command`
    """
```

2020-08-10 22:56 UTC, retke commented on tournamentmanager/tournamentmanager.py
> +        embed.add_field(name="durée du check in", value=check_time, inline=False)
Les majuscules stp 😭 
```suggestion
        embed.add_field(name="Durée du Check-in", value=check_time, inline=False)
```

2020-08-11 11:55 UTC, leElvyn commented on tournamentmanager/progress_menu.py
> +        embed.add_field(name="Temps restant", value="{0}".format(timedelta(seconds=check_time)), inline=False)
Ça c'est mon absence de connaissances des fonctions un peu avancés de python

2021-01-11 21:24 UTC, closed without merging